#Explanation:
#SMTP_ settings should be uncommented and configured if you want to have servicebot send emails
#CERTIFICATES and the certificate volume should be uncommented when you get SSL certs, enter path to
version: '2'
services:
  servicebot:
    image: servicebot/servicebot
    environment:
      CERTIFICATES: "/etc/pki/tls/certs"
      POSTGRES_DB_PORT : "5432"
      POSTGRES_DB_HOST : "db"
      POSTGRES_DB_USER : "oadnc_servicebot_u"
      POSTGRES_DB_PASSWORD : "sbX9BVqA8!Y10CWrB9"
      POSTGRES_DB_NAME : "oadnc_sb_db"
#      SMTP_HOST : 'localhost'
#     SMTP_USER : 'postmaster@localhost'
#      SMTP_PASSWORD : 'password'
#      SMTP_PORT : '587'
      PORT : "3000"
    volumes:
      - upload-data:/usr/src/app/uploads
      - environment-file:/usr/src/app/env
#      - /path/to/ssl/certs/on/server:/usr/src/app/ssl
    links:
      - db
    ports:
      - "80:3000"
      - "443:3001"
    command: ["sh", "-c", "node /usr/src/app/bin/wait-for-it.js db 5432  && npm run-script start"]
  db:
    image: postgres
    environment:
      POSTGRES_USER : "oadnc_servicebot_u"
      POSTGRES_PASSWORD : "sbX9BVqA8!Y10CWrB9!"
      POSTGRES_DB : "oadnc_sb_db"
    volumes:
      - db-data:/var/lib/pgsql/data
    expose:
      - "5432"
volumes:
  upload-data:
  environment-file:
  db-data:
